enum AdminManageMutationType {
    SET_LIST='SET_LIST',
    ADMIN_TOTAL='ADMIN_TOTAL',
    ADMIN_PAGE_SIZE='ADMIN_PAGE_SIZE',
    ADMIN_PAGE_END='ADMIN_PAGE_END',
    UPDATE_LIST='UPDATE_LIST',
    PASSWORD_CHANGE='PASSWORD_CHANGE',
    ADMIN_DETAIL='ADMIN_DETAIL',
    UPDATE_CROWD_LIST='UPDATE_CROWD_LIST',
    UPDATE_CROWD_DETAIL='UPDATE_CROWD_DETAIL'
}

export { AdminManageMutationType };
