enum AppSettingActionType {
    FAQ_LIST='FAQ_LIST',
    FAQ_DETAIL='FAQ_DETAIL',
    NOTICE_LIST='NOTICE_LIST',
    NOTICE_FILTER_TO_LIST='NOTICE_FILTER_TO_LIST',
    NOTICE_DETAIL='NOTICE_DETAIL',
    TERMS_LIST='TERMS_LIST',
    TERMS_DETAIL='TERMS_DETAIL',
    TERMS_DETAIL_MODIFY_LIST='TERMS_DETAIL_MODIFY_LIST',
    APP_VERSION_LIST='APP_VERSION_LIST'
}

export { AppSettingActionType };
