enum AppSettingMutationType {
    IS_FILTER='IS_FILTER',
    SET_FILTER='SET_FILTER',
    RESET_FILTER='RESET_FILTER',
    SET_LIST='SET_LIST',
    SET_NOTICE_DETAIL='SET_NOTICE_DETAIL',
    NOTICE_TOTAL='NOTICE_TOTAL',
    NOTICE_PAGE_SIZE='NOTICE_PAGE_SIZE',
    NOTICE_PAGE_END='NOTICE_PAGE_END',
    UPDATE_LIST='UPDATE_LIST',
    UPDATE_TERMS_LIST='UPDATE_TERMS_LIST',
    SET_TERMS_LIST='SET_TERMS_LIST',
    SET_TERMS_DETAIL='SET_TERMS_DETAIL',
    UPDATE_FAQ_LIST='UPDATE_FAQ_LIST',
    SET_FAQ_LIST='SET_FAQ_LIST',
    SET_FAQ_DETAIL='SET_FAQ_DETAIL',
    SET_DETAIL_MODIFY_LIST='SET_DETAIL_MODIFY_LIST',
    UPDATE_DETAIL_MODIFY_LIST='UPDATE_DETAIL_MODIFY_LIST',
    UPDATE_APP_VERSION_LIST='UPDATE_APP_VERSION_LIST'

}

export { AppSettingMutationType };
