enum CommunityMutationType {
    SET_TIMELINE_TYPE='SET_TIMELINE_TYPE',
    UPDATE_TIMELINE_LIST='UPDATE_TIMELINE_LIST',
    UPDATE_FAN_POST_LIST='UPDATE_FAN_POST_LIST',
    UPDATE_FAN_POST_DETAIL='UPDATE_FAN_POST_DETAIL',
    UPDATE_REPORT_LIST='UPDATE_REPORT_LIST',
    UPDATE_REPORT_DETAIL='UPDATE_REPORT_DETAIL',
    UPDATE_REPORT_MEMBER_LIST='UPDATE_REPORT_MEMBER_LIST',
    IS_FILTER='IS_FILTER',
    SET_FILTER='SET_FILTER',
    RESET_FILTER='RESET_FILTER',
}

export {CommunityMutationType};
