enum CommunityActionType {
    TIMELINE_LIST='TIMELINE_LIST',
    FAN_POST_LIST='FAN_POST_LIST',
    FAN_POST_DETAIL_VIEW='FAN_POST_DETAIL_VIEW',
    REPORT_LIST='REPORT_LIST',
    REPORT_DETAIL_VIEW='REPORT_DETAIL_VIEW',
    POST_REPORT_MEMBER_LIST='POST_REPORT_MEMBER_LIST',
    REPLY_REPORT_MEMBER_LIST='REPLY_REPORT_MEMBER_LIST'
}

export {CommunityActionType};
