enum DirectViewMutaionType {
  IS_FILTER = 'IS_FILTER',
  SET_FILTER = 'SET_FILTER',
  RESET_FILTER = 'RESET_FILTER',
  VICTORY_LIST = 'VICTORY_LIST',
  VICTORY_TOTAL = 'VICTORY_TOTAL',
  UPDATE_VICTORY_LIST = 'UPDATE_VICTORY_LIST',
  VICTORY_PAGE_SIZE = 'VICTORY_PAGE_SIZE',
  VICTORY_PAGE_END = 'VICTORY_PAGE_END',
  UPDATE_CHECKIN_LIST = 'UPDATE_CHECKIN_LIST',
  UPDATE_CHECKIN_DETAIL = 'UPDATE_CHECKIN_DETAIL',
}

export {DirectViewMutaionType};
