enum EventMgMutationType {
    IS_FILTER='IS_FILTER',
    SET_FILTER='SET_FILTER',
    RESET_FILTER='RESET_FILTER',
    GIFT_TOTAL='GIFT_TOTAL',
    GIFT_PAGE_SIZE='GIFT_PAGE_SIZE',
    GIFT_PAGE_END='GIFT_PAGE_END',
    UPDATE_GIFT_LIST='UPDATE_GIFT_LIST',
    UPDATE_GIFT_DETAIL='UPDATE_GIFT_DETAIL',
    UPDATE_EVENT_LIST='UPDATE_LIST',
    UPDATE_LIVE_LIST='UPDATE_LIVE_LIST',
    UPDATE_LIVE_DETAIL='UPDATE_LIVE_DETAIL',
    UPDATE_ENTER_LIVE_EVENT='UPDATE_ENTER_LIVE_EVENT',
    UPDATE_LIVE_EVENT_WINNER='UPDATE_LIVE_EVENT_WINNER',
    SET_GAME='SET_GAME',
    UPDATE_GENERAL_DETAIL='UPDATE_GENERAL_DETAIL',
    UPDATE_ENTER_GENERAL_EVENT='UPDATE_ENTER_GENERAL_EVENT',
    UPDATE_GENERAL_EVENT_WINNER='UPDATE_GENERAL_EVENT_WINNER'
}

export { EventMgMutationType };
