enum EventMgActionType {
  GIFT_LIST='GIFT_LIST',
  GIFT_FILTER_TO_LIST='GIFT_FILTER_TO_LIST',
  GIFT_DETAIL='GIFT_DETAIL',
  EVENT_LIST='EVENT_LIST',
  LIVE_LIST='LIVE_LIST',
  LIVE_FILTER_TO_LIST='LIVE_FILTER_TO_LIST',
  LIVE_DETAIL_VIEW='LIVE_DETAIL_VIEW',
  ENTER_LIVE_EVENT='ENTER_LIVE_EVENT',
  LIVE_EVENT_WINNER='LIVE_EVENT_WINNER',
  GAME_LIST='GAME_LIST',
  GENERAL_FILTER_TO_LIST='GENERAL_FILTER_TO_LIST',
  GENERAL_DETAIL_VIEW='GENERAL_DETAIL_VIEW',
  ENTER_GENERAL_EVENT='ENTER_GENERAL_EVENT',
  GENERAL_EVENT_WINNER='GENERAL_EVENT_WINNER'
}

export { EventMgActionType };
