enum MembershipMutationType {
    UPDATE_MEMBERSHIP_LIST='UPDATE_MEMBERSHIP_LIST',
    UPDATE_MEMBERSHIP_DETAIL='UPDATE_MEMBERSHIP_DETAIL',
    UPDATE_POINT_HISTORY='UPDATE_POINT_HISTORY'
}

export {MembershipMutationType};
