enum NotiActionType {
    PUSH_LIST = 'PUSH_LIST',
    PUSH_DETAIL_VIEW = 'PUSH_DETAIL_VIEW',
    LIVE_EVENT_LIST='LIVE_EVENT_LIST',
    GENERAL_EVENT_LIST='GENERAL_EVENT_LIST',
    EMAIL_LIST = 'EMAIL_LIST',
    EMAIL_TEMPLATE = 'EMAIL_TEMPLATE'
}

export {NotiActionType};
