enum NotiMutationType {
    UPDATE_PUSH_LIST='UPDATE_PUSH_LIST',
    UPDATE_PUSH_DETAIL='UPDATE_PUSH_DETAIL',
    UPDATE_LIVE_EVENT_LIST='UPDATE_LIVE_EVENT_LIST',
    UPDATE_GENERAL_EVENT_LIST='UPDATE_GENERAL_EVENT_LIST',
    UPDATE_EMAIL_LIST='UPDATE_EMAIL_LIST',
    UPDATE_EMAIL_TEMPLATE='UPDATE_EMAIL_TEMPLATE',
    UPDATE_EMAIL_PAGE='UPDATE_EMAIL_PAGE'
}

export {NotiMutationType};
